version: '{build}'
image: Visual Studio 2017
configuration: Release
platform: Any CPU
cache:
- packages -> **\packages.config
- '%USERPROFILE%\.nuget\packages -> **\project.json'
before_build:
- cmd: >-
    FOR /F %%i in ('git describe --always --tags') do set GIT_TAG=%%i

    nuget restore
build:
  verbosity: minimal
after_build:
- cmd: >-
    type GitVersion.cs

    cd Build

    move QuickLook.msi ..\QuickLook-%GIT_TAG%.msi

    dir ..\QuickLook-%GIT_TAG%.msi

    7z a ..\QuickLook-%GIT_TAG%.zip .\Package\* -r

    7z l ..\QuickLook-%GIT_TAG%.zip

artifacts:
- path: QuickLook-%GIT_TAG%.zip
  name: QuickLook-%GIT_TAG%
- path: QuickLook-%GIT_TAG%.msi
  name: QuickLook-%GIT_TAG%
