version: '{build}'
image: Visual Studio 2017
configuration: Release
platform: Any CPU
cache:
- packages -> **\packages.config
- '%USERPROFILE%\.nuget\packages -> **\project.json'
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- cmd: >-
    type GitVersion.cs

    cd Build

    dir QuickLook.msi

    7z a QuickLook.zip .\Package\* -r

    7z l QuickLook.zip
artifacts:
- path: Build\QuickLook.zip
  name: QuickLook
- path: Build\QuickLook.msi
  name: QuickLook
