version: '{build}'
image: Visual Studio 2017
configuration: Release
platform: Any CPU
cache:
- packages -> **\packages.config
- '%USERPROFILE%\.nuget\packages -> **\project.json'
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- cmd: >-
    type GitVersion.cs
    cd Build
    move QuickLook.msi ..\QuickLook-%APPVEYOR_REPO_TAG_NAME%.msi
    dir ..\QuickLook-%APPVEYOR_REPO_TAG_NAME%.msi
    7z a ..\QuickLook-%APPVEYOR_REPO_TAG_NAME%.zip .\Package\* -r
    7z l ..\QuickLook-%APPVEYOR_REPO_TAG_NAME%.zip
artifacts:
- path: QuickLook-$(APPVEYOR_REPO_TAG_NAME).zip
  name: QuickLook-$(APPVEYOR_REPO_TAG_NAME)
- path: QuickLook-$(APPVEYOR_REPO_TAG_NAME).msi
  name: QuickLook-$(APPVEYOR_REPO_TAG_NAME)
deploy:
- provider: GitHub
  auth_token:
    secure: YwPL9DCYIWsHKBT7WMnx+IHTWph9fEOUBpnfZhZMTgz6VzWem01X+l/vZPlFxCG/
  artifact: QuickLook-$(APPVEYOR_REPO_TAG_NAME)
  draft: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true